<?php
// Display the cars which have been added into the reservation shopping cart (using SESSION)
// Initialise the session if session is yet to initialised
if (!isset($_SESSION)) {
  session_start();
}

// Store the added products in an array, create empty array if not yet created
if (empty($_SESSION['cart'])) {
  $_SESSION['cart'] = array();
}

// Update session variable only if the id parameter is passed thru url
if (!empty($_GET['id'])) {
  array_push($_SESSION['cart'], $_GET['id']);
  $_SESSION['cart'] = array_unique($_SESSION['cart']); //removing repeated product ID
}
?>

<?php
	include ("header.php");
?>
<section id="main">
	<h2>Shopping Cart</h2><br>
   <div class="cart">
      <p id="emptyCartMessage" style="display:block;">Empty Cart - Looks like you haven't made your choice yet.</p>
      <table width="90%" border="2" cellpadding="4" id="cart" style="margin:auto">
        <!-- <tr> auto-generated by JavaScript -->
      </table>
      <br>
      <form name="cart" method="post" action="checkout.php" onSubmit="return checkInput()">
        <input type="hidden" id="productInCart" name="productInCart" value="">
        <input type="hidden" id="totalCost" name="totalCost" value="">
        <button type="submit" name="submit" value="submit" class="checkout btn">PROCEED TO CHECKOUT</button>
      </form>
    </div>
</section>
</div>

<script>var selectedProduct = <?php echo '["' . implode('", "', $_SESSION['cart']) . '"]';?>;</script>
<script src="./js/readxml.js"></script>
<script src="./js/cartgenerator.js"></script>

<?php
	include ("footer.php");
?>
